---
- name: Install, start, and enable Apache
  hosts: ansible-host01
  tasks:
  - name: Install Apache
    package:
      name: apache2
      state: latest
  - name: Start and enable Apache service
    service:
      name: apache2
      state: started
      enabled: yes
...

